name: plbenchmark
channels:
  - conda-forge
dependencies:
    # Base depends
  - python<3.12
  - pip

    # Testing
  - pytest
  - pytest-cov
  - codecov
  - nbval
  - coverage

  - pyyaml
  - numpy<2.0.0
  - matplotlib
  - pandas
  - rdkit=2023.03.3
  - networkx
  - openff-units
  - scipy
  - ambertools=23.3
  - openff-toolkit<=0.11
  - requests
  - git-lfs
  - nbsphinx     
